version: '2.1'

services:
  zoo:
    image: zookeeper:3.4.9
    hostname: zoo
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA LISTENERS explain
      # 1. https://medium.com/@iamsuraj/what-is-advertised-listeners-in-kafka-72e6fae7d68e
      # 2. https://rmoff.net/2018/08/02/kafka-listeners-explained/
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:9091,LISTENER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
    depends_on:
      - zoo
  kafdrop:
    image: obsidiandynamics/kafdrop:3.23.0
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9091
    depends_on:
      - kafka